# Generated by Django 4.1 on 2022-09-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ns_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
